global:
  extraPodAnnotations: {}

  extraLabels: {}

  prometheusAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

  env:
    httpsProxy:
    noProxy: 10.0.0.0/8,172.0.0.0/8

kraan:
  crd:
    enabled: true
  rbac:
    enabled: true
    adminClusterRole:
      # admin ClusterRole to be used by the controller, default is cluster-admin
      name: "cluster-admin"
      # specify rules to create a ClusterRole
      # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#policyrule-v1-rbac-authorization-k8s-io
      rules: []
    adminClusterRoleBinding:
      name: "kraan-deployer"
  netpolicy:
    enabled: true
  kraanController:
    enabled: true
    name: kraan-controller

    extraPodAnnotations: {}

    extraLabels: {}

    extraArgs: []

    prometheus:
      enabled: true

    imagePullSecrets:
      name:

    image:
      repository: kraan
      name: kraan-controller
      tag:
      imagePullPolicy:

    args:
      logLevel: 0
      syncPeriod: 1m

    readOnly: true

    runAsNonRoot: false

    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi

    tolerations:
      []
      # - key: "key"
      #   operator: "Equal|Exists"
      #   value: "value"
      #   effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

    ## Node labels for alertmanager pod assignment
    ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
    ##
    nodeSelector: {}

    ## Pod affinity
    ##
    affinity: {}

    ## https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/
    ##
    priorityClassName: {}
    preemptionPolicy: {}
    priority: {}

gotk:
  rbac:
    enabled: true
    adminClusterRole:
      # admin ClusterRole to be used by the controller, default is cluster-admin
      name: "cluster-admin"
      # specify rules to create a ClusterRole
      # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#policyrule-v1-rbac-authorization-k8s-io
      rules: []
    adminClusterRoleBinding:
      name: "cluster-reconciler"
  netpolicy:
    enabled: true

  sourceController:
    crd:
      enabled: true
    enabled: true

    name: source-controller

    extraPodAnnotations: {}

    extraLabels: {}

    extraArgs: []

    prometheus:
      enabled: true

    image:
      repository: ghcr.io/fluxcd
      name: source-controller
      tag: v1.6.0
      imagePullPolicy:

    imagePullSecrets:
      name:

    proxy: true

    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi

    tolerations:
      []
      # - key: "key"
      #   operator: "Equal|Exists"
      #   value: "value"
      #   effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

    ## Node labels for alertmanager pod assignment
    ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
    ##
    nodeSelector: {}

    ## Pod affinity
    ##
    affinity: {}

    ## https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/
    ##
    priorityClassName: {}
    preemptionPolicy: {}
    priority: {}

  helmController:
    crd:
      enabled: true
    enabled: true

    name: helm-controller

    extraPodAnnotations: {}

    extraLabels: {}

    extraArgs: []

    prometheus:
      enabled: true

    imagePullSecrets:
      name:

    image:
      repository: ghcr.io/fluxcd
      name: helm-controller
      tag: v1.3.0
      imagePullPolicy:

    proxy: true

    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi

    tolerations:
      []
      # - key: "key"
      #   operator: "Equal|Exists"
      #   value: "value"
      #   effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

    ## Node labels for alertmanager pod assignment
    ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
    ##
    nodeSelector: {}

    ## Pod affinity
    ##
    affinity: {}

    ## https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/
    ##
    priorityClassName: {}
    preemptionPolicy: {}
    priority: {}

  networkPolicy:
    enabled: true
    namespaceSelector: {}
