// Code generated by MockGen. DO NOT EDIT.
// Source: execProvider.go

package mockkubectl

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockExecProvider is a mock of ExecProvider interface
type MockExecProvider struct {
	ctrl     *gomock.Controller
	recorder *MockExecProviderMockRecorder
}

// MockExecProviderMockRecorder is the mock recorder for MockExecProvider
type MockExecProviderMockRecorder struct {
	mock *MockExecProvider
}

// NewMockExecProvider creates a new mock instance
func NewMockExecProvider(ctrl *gomock.Controller) *MockExecProvider {
	mock := &MockExecProvider{ctrl: ctrl}
	mock.recorder = &MockExecProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockExecProvider) EXPECT() *MockExecProviderMockRecorder {
	return _m.recorder
}

// findOnPath mocks base method
func (_m *MockExecProvider) findOnPath(file string) (string, error) {
	ret := _m.ctrl.Call(_m, "findOnPath", file)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// findOnPath indicates an expected call of findOnPath
func (_mr *MockExecProviderMockRecorder) findOnPath(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "findOnPath", reflect.TypeOf((*MockExecProvider)(nil).findOnPath), arg0)
}

// execCmd mocks base method
func (_m *MockExecProvider) execCmd(name string, arg ...string) ([]byte, error) {
	_s := []interface{}{name}
	for _, _x := range arg {
		_s = append(_s, _x)
	}
	ret := _m.ctrl.Call(_m, "execCmd", _s...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// execCmd indicates an expected call of execCmd
func (_mr *MockExecProviderMockRecorder) execCmd(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	_s := append([]interface{}{arg0}, arg1...)
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "execCmd", reflect.TypeOf((*MockExecProvider)(nil).execCmd), _s...)
}
