// Code generated by MockGen. DO NOT EDIT.
// Source: kubectl.go

package mockkubectl

import (
	logr "github.com/go-logr/logr"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockKubectl is a mock of Kubectl interface
type MockKubectl struct {
	ctrl     *gomock.Controller
	recorder *MockKubectlMockRecorder
}

// MockKubectlMockRecorder is the mock recorder for MockKubectl
type MockKubectlMockRecorder struct {
	mock *MockKubectl
}

// NewMockKubectl creates a new mock instance
func NewMockKubectl(ctrl *gomock.Controller) *MockKubectl {
	mock := &MockKubectl{ctrl: ctrl}
	mock.recorder = &MockKubectlMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockKubectl) EXPECT() *MockKubectlMockRecorder {
	return _m.recorder
}

// Apply mocks base method
func (_m *MockKubectl) Apply(path string) Command {
	ret := _m.ctrl.Call(_m, "Apply", path)
	ret0, _ := ret[0].(Command)
	return ret0
}

// Apply indicates an expected call of Apply
func (_mr *MockKubectlMockRecorder) Apply(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Apply", reflect.TypeOf((*MockKubectl)(nil).Apply), arg0)
}

// Delete mocks base method
func (_m *MockKubectl) Delete(args ...string) Command {
	_s := []interface{}{}
	for _, _x := range args {
		_s = append(_s, _x)
	}
	ret := _m.ctrl.Call(_m, "Delete", _s...)
	ret0, _ := ret[0].(Command)
	return ret0
}

// Delete indicates an expected call of Delete
func (_mr *MockKubectlMockRecorder) Delete(arg0 ...interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Delete", reflect.TypeOf((*MockKubectl)(nil).Delete), arg0...)
}

// Get mocks base method
func (_m *MockKubectl) Get(args ...string) Command {
	_s := []interface{}{}
	for _, _x := range args {
		_s = append(_s, _x)
	}
	ret := _m.ctrl.Call(_m, "Get", _s...)
	ret0, _ := ret[0].(Command)
	return ret0
}

// Get indicates an expected call of Get
func (_mr *MockKubectlMockRecorder) Get(arg0 ...interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Get", reflect.TypeOf((*MockKubectl)(nil).Get), arg0...)
}

// getLogger mocks base method
func (_m *MockKubectl) getLogger() logr.Logger {
	ret := _m.ctrl.Call(_m, "getLogger")
	ret0, _ := ret[0].(logr.Logger)
	return ret0
}

// getLogger indicates an expected call of getLogger
func (_mr *MockKubectlMockRecorder) getLogger() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "getLogger", reflect.TypeOf((*MockKubectl)(nil).getLogger))
}

// getPath mocks base method
func (_m *MockKubectl) getPath() string {
	ret := _m.ctrl.Call(_m, "getPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// getPath indicates an expected call of getPath
func (_mr *MockKubectlMockRecorder) getPath() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "getPath", reflect.TypeOf((*MockKubectl)(nil).getPath))
}

// MockCommand is a mock of Command interface
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCommandMockRecorder
}

// MockCommandMockRecorder is the mock recorder for MockCommand
type MockCommandMockRecorder struct {
	mock *MockCommand
}

// NewMockCommand creates a new mock instance
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &MockCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockCommand) EXPECT() *MockCommandMockRecorder {
	return _m.recorder
}

// Run mocks base method
func (_m *MockCommand) Run() ([]byte, error) {
	ret := _m.ctrl.Call(_m, "Run")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run
func (_mr *MockCommandMockRecorder) Run() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Run", reflect.TypeOf((*MockCommand)(nil).Run))
}

// DryRun mocks base method
func (_m *MockCommand) DryRun() ([]byte, error) {
	ret := _m.ctrl.Call(_m, "DryRun")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DryRun indicates an expected call of DryRun
func (_mr *MockCommandMockRecorder) DryRun() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "DryRun", reflect.TypeOf((*MockCommand)(nil).DryRun))
}

// WithLogger mocks base method
func (_m *MockCommand) WithLogger(logger logr.Logger) *abstractCommand {
	ret := _m.ctrl.Call(_m, "WithLogger", logger)
	ret0, _ := ret[0].(*abstractCommand)
	return ret0
}

// WithLogger indicates an expected call of WithLogger
func (_mr *MockCommandMockRecorder) WithLogger(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "WithLogger", reflect.TypeOf((*MockCommand)(nil).WithLogger), arg0)
}
