// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fidelity/kraan/pkg/internal/kubectl (interfaces: Kubectl,Command)

// Package mocks is a generated GoMock package.
package mocks

import (
	kubectl "github.com/fidelity/kraan/pkg/internal/kubectl"
	logr "github.com/go-logr/logr"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockKubectl is a mock of Kubectl interface
type MockKubectl struct {
	ctrl     *gomock.Controller
	recorder *MockKubectlMockRecorder
}

// MockKubectlMockRecorder is the mock recorder for MockKubectl
type MockKubectlMockRecorder struct {
	mock *MockKubectl
}

// NewMockKubectl creates a new mock instance
func NewMockKubectl(ctrl *gomock.Controller) *MockKubectl {
	mock := &MockKubectl{ctrl: ctrl}
	mock.recorder = &MockKubectlMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockKubectl) EXPECT() *MockKubectlMockRecorder {
	return m.recorder
}

// Apply mocks base method
func (m *MockKubectl) Apply(arg0 string) kubectl.Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", arg0)
	ret0, _ := ret[0].(kubectl.Command)
	return ret0
}

// Apply indicates an expected call of Apply
func (mr *MockKubectlMockRecorder) Apply(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockKubectl)(nil).Apply), arg0)
}

// Delete mocks base method
func (m *MockKubectl) Delete(arg0 ...string) kubectl.Command {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(kubectl.Command)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockKubectlMockRecorder) Delete(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockKubectl)(nil).Delete), arg0...)
}

// Get mocks base method
func (m *MockKubectl) Get(arg0 ...string) kubectl.Command {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(kubectl.Command)
	return ret0
}

// Get indicates an expected call of Get
func (mr *MockKubectlMockRecorder) Get(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockKubectl)(nil).Get), arg0...)
}

// MockCommand is a mock of Command interface
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCommandMockRecorder
}

// MockCommandMockRecorder is the mock recorder for MockCommand
type MockCommandMockRecorder struct {
	mock *MockCommand
}

// NewMockCommand creates a new mock instance
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &MockCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCommand) EXPECT() *MockCommandMockRecorder {
	return m.recorder
}

// Build mocks base method
func (m *MockCommand) Build() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build")
	ret0, _ := ret[0].(string)
	return ret0
}

// Build indicates an expected call of Build
func (mr *MockCommandMockRecorder) Build() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockCommand)(nil).Build))
}

// DryRun mocks base method
func (m *MockCommand) DryRun() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DryRun")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DryRun indicates an expected call of DryRun
func (mr *MockCommandMockRecorder) DryRun() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DryRun", reflect.TypeOf((*MockCommand)(nil).DryRun))
}

// Run mocks base method
func (m *MockCommand) Run() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run
func (mr *MockCommandMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockCommand)(nil).Run))
}

// WithLogger mocks base method
func (m *MockCommand) WithLogger(arg0 logr.Logger) kubectl.Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithLogger", arg0)
	ret0, _ := ret[0].(kubectl.Command)
	return ret0
}

// WithLogger indicates an expected call of WithLogger
func (mr *MockCommandMockRecorder) WithLogger(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithLogger", reflect.TypeOf((*MockCommand)(nil).WithLogger), arg0)
}

// asString mocks base method
func (m *MockCommand) asString() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "asString")
	ret0, _ := ret[0].(string)
	return ret0
}

// asString indicates an expected call of asString
func (mr *MockCommandMockRecorder) asString() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "asString", reflect.TypeOf((*MockCommand)(nil).asString))
}

// getArgs mocks base method
func (m *MockCommand) getArgs() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getArgs")
	ret0, _ := ret[0].([]string)
	return ret0
}

// getArgs indicates an expected call of getArgs
func (mr *MockCommandMockRecorder) getArgs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getArgs", reflect.TypeOf((*MockCommand)(nil).getArgs))
}

// getPath mocks base method
func (m *MockCommand) getPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// getPath indicates an expected call of getPath
func (mr *MockCommandMockRecorder) getPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getPath", reflect.TypeOf((*MockCommand)(nil).getPath))
}

// getSubCmd mocks base method
func (m *MockCommand) getSubCmd() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getSubCmd")
	ret0, _ := ret[0].(string)
	return ret0
}

// getSubCmd indicates an expected call of getSubCmd
func (mr *MockCommandMockRecorder) getSubCmd() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getSubCmd", reflect.TypeOf((*MockCommand)(nil).getSubCmd))
}

// isJSONOutput mocks base method
func (m *MockCommand) isJSONOutput() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "isJSONOutput")
	ret0, _ := ret[0].(bool)
	return ret0
}

// isJSONOutput indicates an expected call of isJSONOutput
func (mr *MockCommandMockRecorder) isJSONOutput() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "isJSONOutput", reflect.TypeOf((*MockCommand)(nil).isJSONOutput))
}
